---
- apt:
    name: ['build-essential', 'curl', 'git', 'file']
  environment: "{{ env | default({}) }}"

- user:
    name: linuxbrew
    uid: 3000
    shell: /bin/bash

- shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  become: true
  become_user: linuxbrew
  environment: "{{ env | default({}) | combine({ 'CI': 1 }) }}"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin

- shell: "cat /home/linuxbrew/.profile | grep \\\\.linuxbrew || echo ''"
  register: test_profile_linuxbrew
  changed_when: false
  become: true
  become_user: linuxbrew

- shell: echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"' >> /home/linuxbrew/.profile
  become: true
  become_user: linuxbrew
  when: test_profile_linuxbrew.stdout == ""
