---
- name: install docker
  shell: wget -qO- https://get.docker.com/ | sh
  environment: "{{ env | default({}) }}"
  args:
    creates: /usr/bin/docker

- shell: "/usr/local/bin/docker-compose --version"
  register: installed_docker_compose
  changed_when: false
  ignore_errors: true
  args:
    removes: /usr/local/bin/docker-compose

- name: install docker-compose
  shell: "curl -s -L https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
  environment: "{{ env | default({}) }}"
  when: "installed_docker_compose.stdout.find('{{docker_compose_version}}') == -1"

- file: path=/usr/local/bin/docker-compose mode="a+x"

- shell: "/usr/local/bin/docker-volumes --version"
  register: installed_docker_volumes
  changed_when: false
  ignore_errors: true
  args:
    removes: /usr/local/bin/docker-volumes

- name: install docker-volumes
  shell: "curl -s -L https://github.com/cpuguy83/docker-volumes/releases/download/v1.{{docker_volumes_version}}/docker-volumes-`uname -s | tr '[:upper:]' '[:lower:]'`-`dpkg --print-architecture` > /usr/local/bin/docker-volumes"
  environment: "{{ env | default({}) }}"
  when: "installed_docker_volumes.stdout != 'docker-volumes version {{docker_volumes_version}}'"

- file: path=/usr/local/bin/docker-volumes mode="a+x"

- copy: dest=/etc/logrotate.d/docker-container src=docker-container.logrotate
