---
- apt:
    name:
      - curl
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - gnupg-agent
  environment: "{{ env | default({}) }}"

- apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
  environment: "{{ env | default({}) }}"

- shell: "dpkg --print-architecture"
  register: dpkg_architecture_register
  changed_when: false

- set_fact:
    dpkg_architecture: "{{dpkg_architecture_register.stdout}}"

- apt_repository:
    repo: deb [arch={{dpkg_architecture}}] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable
    filename: docker
  environment: "{{ env | default({}) }}"

- apt:
    name: docker-ce
    update_cache: yes
  environment: "{{ env | default({}) }}"

- copy: dest=/etc/docker/daemon.json src=daemon.json force=no

- file: dest=/etc/systemd/system/docker.service.d state=directory
- copy: dest=/etc/systemd/system/docker.service.d/system-default.conf src=service.system-default.conf

- name: check linuxbrew
  shell: which brew
  register: check_linuxbrew
  ignore_errors: true
  changed_when: false

- homebrew:
    name:
      - ctop
      - docker-compose
  become: true
  become_user: linuxbrew
  environment: "{{ env | default({}) }}"
  when: check_linuxbrew.rc == 0
