---
- homebrew: name={{item.name}} install_options={{ item.options | default() }} state=latest
  environment: "{{ env | default({}) }}"
  with_items:
    - { name: rbenv }
    - { name: ruby-build, options: without-autoconf,without-openssl,without-pkg-config }
    - { name: rbenv-gem-rehash }

- copy: dest=/etc/profile.d/rbenv.sh src=rbenv.init.sh

- name: install ruby-build build environment
  apt: name={{item}} state=latest
  environment: "{{ env | default({}) }}"
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6
    - libreadline6-dev
    - zlib1g
    - zlib1g-dev